[api]
enabled = true

[functions.webhook]
verify_jwt = false

[functions.form-lead]
verify_jwt = false

[functions.webchat]
verify_jwt = false

[functions.followup]
verify_jwt = false

[functions.gerar-criativo]
verify_jwt = false

[functions.disparo]
verify_jwt = false

[functions.onboarding]
verify_jwt = false

[functions.onboarding-link]
verify_jwt = false

[functions.onboarding-cred-ver]
verify_jwt = false
